# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory to /app
WORKDIR /app/backend

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY . .

# OpenAPI docs are at /docs, redoc at /redoc
EXPOSE 8000

# Run the command to start uWSGI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]