on:
    push:
      branches:
      - main
      paths:
      - 'app/**'
      - '.github/workflows/Python-ACA-Deploy.yml'

env:
workingDir: '${{ github.workspace }}/app'
ProjectName: 'acapoker'

jobs:
build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: Azure/login@v1
    with:
        creds: '{
                "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
                }'

    - uses: Azure/get-keyvault-secrets@v1
    with:
        keyvault: '${{ env.ProjectName }}-kv' # name of key vault in Azure portal
        secrets: 'aca-url, aca-user, aca-pass'  # comma separated list of secret keys to fetch from key vault 
    id: acaKeyVault # ID for secrets that you will reference

    - name: Build and deploy backend Container App
    uses: azure/container-apps-deploy-action@v1
    with:
        appSourcePath: '${{ env.workingDir }}/backend'
        resourceGroup: ${{ env.ProjectName }}
        containerAppEnvironment: ${{ env.ProjectName }}-ace
        containerAppName: ${{ env.ProjectName }}-be-aca
        targetPort: 8000
        imageToBuild: ${{ steps.acaKeyVault.outputs.aca-url }}/${{ env.ProjectName }}-be-aca:${{ github.sha }}
        acrName: ${{ env.ProjectName }}acr
        acrUsername: ${{ steps.acaKeyVault.outputs.aca-user }}
        acrPassword: ${{ steps.acaKeyVault.outputs.aca-pass }}